title: jeonghopark' blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: JeongHo Park # add your name
author-img: jeonghopark_760x760_red_b_edit_bw.jpg # add your photo
about-author: Artist working with Code, Algorithmic Composer, Lecturer # add description
social-twitter: jeonghopark # add your Twitter handle
# social-facebook: jeonghopark.net # add your Facebook handle
social-instagram: jeonghopark # add your Instagram handle
social-github: jeonghopark # add your Github handle
social-email: jeonghopark@jeonghopark.de # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
